<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <!-- Publishing -->
  <PropertyGroup>
    <AssemblyName>game</AssemblyName>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Game.FSharp\Game.FSharp.fsproj" />
  </ItemGroup>

</Project>
