<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ApplicationManifest>App.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <!-- Publishing -->
  <PropertyGroup>
    <AssemblyName>start</AssemblyName>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <SelfContained Condition="'$(RuntimeIdentifier)' != ''">true</SelfContained>
    <!--<PublishDir>$(MSBuildThisFileDirectory)..\..\build\</PublishDir>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <!--<PackageReference Include="Avalonia.Themes.Simple" Version="12.1.1" />-->
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

</Project>
